### ISSUE TITLE
Create working sidebar

### ISSUE THREAD

**Issue by makssmeinart** [makssmeinart/boocampTest#10]
Description

** TODO **

- [ ]  Create sidebar component
- [ ]  Create sidebar redux reducer && slice
- [ ]  Setup data flow on the sidebar load
