### ISSUE TITLE
Create main content

### ISSUE THREAD

**Issue by makssmeinart** [makssmeinart/boocampTest#12]
Description

Okay so now we need to create main cat's content: We need state for cats and data that we will put inside of the query. Also we need to create components to display cats.

** TODO **

- [ ] Create BL ( New slice. Thunk, Services ect... )
- [ ] Create UI ( Everything should be responsive )
- [ ] Connect navbar links to BL when finished.
